# Generated by Django 4.2.20 on 2025-03-15 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
            ],
            options={
                'indexes': [models.Index(fields=['label'], name='wallets_wal_label_e47896_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['wallet'], name='wallets_tra_wallet__757bec_idx'), models.Index(fields=['txid'], name='wallets_tra_txid_8d45b1_idx')],
            },
        ),
    ]
